name: Build Docker Images

on:
  pull_request:
    branches:
      - main

jobs:
  build-docker:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ matrix.directory }}
    strategy:
      matrix:
        directory: [
          data_prep,
          train,
          eval
        ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract component name
        id: extract-component-name
        run: echo "component_name=$(basename ${{ matrix.directory }})" >> $GITHUB_OUTPUT

      - name: Build Docker
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.directory }}
          tags: ${{ steps.extract-component-name.outputs.component_name }}:latest